<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>


<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $translate('Item'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<?php echo $item->displayValues(); ?>

<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<!-- MAPPING -->
<!-- div with geojson, populated by php call to api -->
<div id="item-geojson" style="display:none"><?php
echo $item->value('p-lod:geojson', ['type' => 'literal']);
?></div>


<div id="mapid" style="width: 800px; height: 600px;display:none"></div>
<script>
// check if the item-geojson div has content and make a map if it does. 
if ($('#item-geojson').html().trim()) {
       $('#mapid').show()

	var mymap = L.map('mapid').setView([40.75, 14.485], 16);

	L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
		maxZoom: 19,
		attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
		id: 'mapbox.streets'
	}).addTo(mymap);

       L.geoJSON(JSON.parse($('#item-geojson').html())).addTo(mymap)
       
}
</script>


<!-- IMAGE DISPLAY -->
<?php
/* use api to get image url and render if there is one. */
 $imgUrl =  $item->value('p-lod:image-url', ['type' => 'uri']);
 if ($imgUrl): ?>
<div id="pipimage"><img style="max-width:300px" src="<?php echo $imgUrl->uri();?>"></img></div>

<?php endif; ?>


<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 250, $property);
?>

<?php if ($subjectValues): ?>
<div id="item-linked">
<!--
    <h4><?php echo $translate('Items that link to ');
              echo $item->displayTitle(); ?>:</h4>
-->
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php

$apiclass = $site->getServiceLocator()->get(HBrowser\Api\Adapter\GetChildren::class);

echo $apiclass;

# TEST DIRECT SQL QUERY

$sql = <<<ENDSQL
SELECT p1.resource_id AS child_id,
               rtypes.value_resource_id AS child_type,
               p1.property_id AS child_to_p1,
               p1.value_resource_id AS parent_id,
               p2.property_id AS prop2_id,
               p2.value_resource_id AS parent2_id,
               p3.property_id AS prop3_id,
               p3.value_resource_id AS parent3_id,
               p4.property_id AS prop4_id,
               p4.value_resource_id AS parent4_id,
               p5.property_id AS prop5_id,
               p5.value_resource_id AS parent5_id,
               p6.property_id AS prop6_id,
               p6.value_resource_id AS parent6_id,
               p7.property_id AS prop7_id,
               p7.value_resource_id AS parent7_id 

FROM        value p1 
LEFT JOIN   value rtypes ON rtypes.resource_id = p1.resource_id AND rtypes.property_id = 289
LEFT JOIN   value p2 ON p2.resource_id = p1.value_resource_id 
LEFT JOIN   value p3 ON p3.resource_id = p2.value_resource_id 
LEFT JOIN   value p4 ON p4.resource_id = p3.value_resource_id  
LEFT JOIN   value p5 ON p5.resource_id = p4.value_resource_id  
LEFT JOIN   value p6 ON p6.resource_id = p5.value_resource_id
LEFT JOIN   value p7 ON p7.resource_id = p6.value_resource_id

WHERE  ?  IN (p1.resource_id,
                   p1.value_resource_id, 
                   p2.value_resource_id, 
                   p3.value_resource_id, 
                   p4.value_resource_id, 
                   p5.value_resource_id, 
                   p6.value_resource_id, 
                   p7.value_resource_id)

AND (p1.property_id IN (305,313,315) OR ISNULL(p1.property_id))
AND (p2.property_id IN (305,313,315) OR ISNULL(p2.property_id))
AND (p3.property_id IN (305,313,315) OR ISNULL(p3.property_id))
AND (p4.property_id IN (305,313,315) OR ISNULL(p4.property_id))
AND (p5.property_id IN (305,313,315) OR ISNULL(p5.property_id))
AND (p6.property_id IN (305,313,315) OR ISNULL(p6.property_id))
AND (p7.property_id IN (305,313,315) OR ISNULL(p7.property_id))
ENDSQL;

$serviceLocator = $site->getServiceLocator();
$connection = $serviceLocator->get('Omeka\Connection');

# $limit = '100';
$bind = array($item->id());
$result = $connection->fetchAll($sql, $bind);
# connection *must* be closed or it will block other queries that this page makes. 
$connection->close();


echo '<pre style="">';
echo print_r($result);
echo '</pre>';

?>


<p>Spatial Hierarchy: 


<?php

$api = $serviceLocator->get('Omeka\ApiManager');

if ($result[0]['parent7_id']) {
$response = $api->read('items', $result[0]['parent7_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
echo ' - ';
}

if ($result[0]['parent6_id']) {
$response = $api->read('items', $result[0]['parent6_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
echo ' - ';
}

if ($result[0]['parent5_id']) {
$response = $api->read('items', $result[0]['parent5_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
echo ' - ';
}

if ($result[0]['parent4_id']) {
$response = $api->read('items', $result[0]['parent4_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
echo ' - ';
}

if ($result[0]['parent3_id']) {
$response = $api->read('items', $result[0]['parent3_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
echo ' - ';
}

if ($result[0]['parent2_id']) {
$response = $api->read('items', $result[0]['parent2_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
echo ' - ';
}

if ($result[0]['parent_id']) {
$response = $api->read('items', $result[0]['parent_id']);
$itemRepresentation = $response->getContent();
echo $itemRepresentation->link($itemRepresentation->title());
}
?></p>

<?php $this->trigger('view.show.:after'); ?>
