<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $translate('Item'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<?php echo $item->displayValues(); ?>

<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<div id="item-geojson" style="display:none"><?php
echo $item->value('p-lod:geojson', ['type' => 'literal']);
?></div>


<div id="mapid" style="width: 800px; height: 600px;display:none"></div>
<script>
if ($('#item-geojson').html().trim()) {
       $('#mapid').show()

	var mymap = L.map('mapid').setView([40.75, 14.485], 16);

	L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
		maxZoom: 19,
		attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
		id: 'mapbox.streets'
	}).addTo(mymap);

       L.geoJSON(JSON.parse($('#item-geojson').html())).addTo(mymap)
       
}
</script>




<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 250, $property);
?>

<?php if ($subjectValues): ?>
<div id="item-linked">
<!--
    <h4><?php echo $translate('Items that link to ');
              echo $item->displayTitle(); ?>:</h4>
-->
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.:after'); ?>
